### ISSUE TITLE
Package version not found

### ISSUE THREAD

**Issue by RemyTinco** [ES-Community/nsecure#53]
## Current behavior
When I'm running `nsecure auto`, the CLI exited after discovering some packages without version number.
Here my log

``` 
⠹ Fetching and walking through all dependencies ...
⠹ Analyzed npm tarballs: [6/13]
⠙ Fetched package metadata: [13/13]
@types/yargs: No matching version found for @types/yargs@undefined.
    at module.exports (/usr/lib/node_modules/nsecure/node_modules/npm-pick-manifest/index.js:207:23)
    at /usr/lib/node_modules/nsecure/node_modules/pacote/lib/registry.js:96:26
    at async createLockDependency (/usr/lib/node_modules/nsecure/src/depWalker.js:303:48) {
  code: 'ETARGET',
  type: 'tag',
  wanted: 'undefined',
  versions: [
    '0.0.14-alpha', '0.0.15-alpha', '0.0.20-alpha', '0.0.21-alpha',
    '0.0.22-alpha', '0.0.23-alpha', '0.0.24-alpha', '0.0.25-alpha',
    '0.0.26-alpha', '0.0.27',       '0.0.28',       '0.0.29',
    '0.0.30',       '0.0.31',       '0.0.32',       '0.0.33',
    '0.0.34',       '0.0.35',       '0.0.36',       '6.3.0',
    '6.3.1',        '6.3.2',        '6.3.3',        '6.5.0',
    '6.6.0',        '8.0.0',        '8.0.1',        '8.0.2',
    '10.0.0',       '8.0.3',        '10.0.1',       '11.0.0',
    '10.0.2',       '11.1.0',       '11.1.1',       '11.1.2',
    '12.0.0',       '12.0.1',       '12.0.2',       '12.0.3',
    '12.0.4',       '12.0.5',       '12.0.6',       '12.0.7',
    '12.0.8',       '12.0.9',       '12.0.10',      '12.0.11',
    '13.0.0',       '12.0.12',      '13.0.1',       '13.0.2',
    '13.0.3',       '12.0.13',      '11.1.3',       '10.0.3',
    '13.0.4',       '12.0.14',      '15.0.0',       '13.0.5',
    '15.0.1',       '13.0.6',       '12.0.15',      '11.1.4',
    '10.0.4',       '8.0.4',        '15.0.2',       '13.0.7',
    '15.0.3',       '13.0.8',       '12.0.16',      '11.1.5',
    '10.0.5',       '15.0.4',       '13.0.9',       '12.0.17',
    '15.0.5',       '13.0.10',      '12.0.18',      '11.1.6',
    '10.0.6',       '8.0.5',        '15.0.6',       '15.0.7',
    '13.0.11',      '12.0.19',      '11.1.7',       '10.0.7',
    '8.0.6'
  ],
  distTags: {
    latest: '15.0.7',
    'ts2.0': '6.6.0',
    'ts2.1': '6.6.0',
    'ts2.2': '12.0.1',
    'ts2.3': '12.0.1',
    'ts2.4': '12.0.1',
    'ts2.5': '12.0.1',
    'ts2.6': '12.0.1',
    'ts2.7': '12.0.1',
    'ts2.8': '12.0.2',
    'ts2.9': '12.0.2',
    'ts3.0': '15.0.5',
    'ts3.1': '15.0.5',
    'ts3.2': '15.0.7',
    'ts3.3': '15.0.7',
    'ts3.4': '15.0.7',
    'ts3.5': '15.0.7',
    'ts3.6': '15.0.7',
    'ts3.7': '15.0.7',
    'ts3.8': '15.0.7',
    'ts3.9': '15.0.7',
    'ts4.0': '15.0.7',
    'ts4.1': '15.0.7'
  },
  defaultTag: 'latest'
}
```

Indeed, most of my package have version, but not this one.
![image](https://user-images.githubusercontent.com/1761380/94371077-045a9e80-00f4-11eb-81cd-15fd099e19b4.png)

## Expected behavior
I expect my `package-lock.json` to be fully analyzed. 
If there are strange packages, I expect a warning.

**Others:**
Because I'm using yarn in this project and I haven't any package-lock.json, I'm doing a `npm shrinkwrap` and renaming the output file in `package-lock.json`
This is version Nsecure 0.4.0
I'm in an Ubuntu Subsystem on Windows 10

**Comment by fraxken** [comment]
Hi,

Should be fixed with https://github.com/ES-Community/nsecure/commit/dadd313cb06d916e7cb65b06b2eaf9b166cad249

Coming soon in the `@next` release (in few days).

By the way nsecure should work even without the package-lock.json (if not please report an issue too). There is also the possibility to disable the lock analysis with the `--no-lock` option.

**Comment by fraxken** [comment]
The new next release is published with the fix in it!
